### **Numpy library에서 자주 사용되는 함수**

- np.array - 배열생성
- np.zeros - 0이 들어있는 배열 생성
- np.ones - 1이 들어있는 배열 생성
- np.empty - 초기화가 없는 값으로 배열을 반환
- np.arange(n) - 배열 버전의 range 함수
- np.random - 다양한 난수가 들어있는 배열 생성
- np.eye: 단위행렬 생성

### 1차원 배열

In [ ]:
import numpy as np
array = np.arange(10)
type(array)
# <class 'numpy.ndarray'>

# 차원: 1차원
array.ndim
# 모양: (10,)
array.shape
# 크기: 10
array.size
# 요소의 데이터 타입: int64
array.dtype

#reshape
array.reshape(2,5)
'''
[[0 1 2 3 4]
 [5 6 7 8 9]]
'''

#concatenate
#axis =0 가로붙이기, axis = 1 세로 붙이기
np.concatenate((array, array), axis = 0)
'''[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]'''


#split 하기 
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
np.split(matrix,[3],axis = 0)
'''
[[ 0]
 [ 4]
 [ 8]
 [12]],

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
'''

### 2차원 배열

In [16]:
import numpy as np
matrix = np.arange(1, 16).reshape(3,5)  #1부터 15까지 들어있는 (3,5)짜리 배열
print(matrix)
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
'''
#인덱싱 하기(2행3열 값 찾기)
print(matrix[2,3])
'''14'''
#슬라이싱 하기(,기준으로 좌측은 행 우측은 열)
print(matrix[0:2,1:4])
'''
[[2 3 4]
 [7 8 9]]
'''

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
14
[[2 3 4]
 [7 8 9]]


'\n[[2 3 4]\n [7 8 9]]\n'

### 3차원 배열

In [14]:
import numpy as np
#3차원에서는 층,행,열 이라고 할수있음
array = np.arange(24).reshape(2,3,4)
print(array)
print('----')
# (2,3,4) Array 자르는것은 axis=0 은 첫번째, axis = 1은 두번째.. 파라미터 기준으로 나눈다고 생각하기.
print(np.split(array,2,axis = 0)[0].shape)
print(np.split(array,2,axis = 0)[0],)
print('----')
print(np.split(array,3,axis = 1)[0].shape)
print(np.split(array,3,axis = 1)[0])
print('----')
print(np.split(array,4,axis = 2)[0].shape)
print(np.split(array,4,axis = 2)[0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----
(1, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
----
(2, 1, 4)
[[[ 0  1  2  3]]

 [[12 13 14 15]]]
----
(2, 3, 1)
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


### 연산

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5])

#단순 연산
print(array + 5)
'''[ 6  7  8  9 10]'''
array2 = np.array([5,4,3,2,1])

#원소끼리 더하기 element wise
print(array + array2)
'''[6 6 6 6 6]'''


#broadcast 연산
A = np.arange(6).reshape(6,1)
B = np.arange(6)
'''[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

[0 1 2 3 4 5]
'''

print(A+B)
'''
[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]
'''

### 집계함수 연산

In [ ]:
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)
'''
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4]
'''
# 집계연산 mean, min,max, std 가능
print(np.sum(matrix))
''' 28'''
# 각 열의 합 구하기
print(np.sum(matrix, axis=0))
'''[ 4  6  8 10]'''