In [2]:
data = [2,1]
mid = len(data)//2
print(mid)
data[:0]
data[0:]

1


[2, 1]

In [5]:
for i in range(3):
    for i in ['A','B','C']:
        print(i)

A
B
C
A
B
C
A
B
C


In [ ]:
import sys

def reservation(meetingList) :
    '''
    회의 일정이 list로 주어질 때, 엘리스씨가 준비해야 하는 회의실의 수의 최솟값을 반환하는 함수를 작성하세요.

    각 일정은 tuple로 주어진다. 예를 들어, 주어진 입력의 경우 다음과 같이 저장된다.
    
    meetingList[0] = (1, 4)
    meetingList[1] = (3, 5)
    meetingList[2] = (2, 7)
    meetingList[3] = (4, 6)
    '''
    m_room = [[] for _ in range(len(meetingList))]
    m_cnt = 0
    for i in range(len(meetingList)):
        if i == 0:
            m_room[0].append(meetingList[i][0])
            m_room[0].append(meetingList[i][1])
            m_cnt +=1
        else:
            for j in range(len(m_room)):
                # print(i,j, m_room,meetingList,m_cnt)
                if m_room[j][1] > meetingList[i][0]: # 미팅룸 끝나는시간이 더늦으면
                    m_room[i].append(meetingList[i][0])
                    m_room[i].append(meetingList[i][1])
                    m_cnt +=1
                else: # 같거나 새로들어오는 시작시간이 더 늦으면
                    m_room[j].append(meetingList[i][0])
                    m_room[j].append(meetingList[i][1])
                break
    return m_cnt

def main():
    '''
    이 부분은 수정하지 마세요.
    '''

    n = int(input())
    meetingList = []

    for i in range(n) :
        data = [int(x) for x in input().split()]
        meetingList.append( (data[0], data[1]) )

    print(reservation(meetingList))

if __name__ == "__main__":
    main()


In [5]:
my_dict = {1:'가',2:'나',3:'다'}
my_dict[1]

'가'

In [6]:
my_dict

{1: '가', 2: '나', 3: '다'}

In [10]:
assert([True,True] == [True,True])

In [11]:
map(int,['1','2','3'])

In [2]:
my_list = [1]
for i in my_list[1:]:
    print(i)

In [5]:
my_dict = {1:'A',2:'B'}
my_list = [2,3]

for i in my_list: # 2, 3
    if my_dict.get(i,-1) != -1:
        print(i, 'check')

2 check


In [7]:
stack = [1,2,3] 

for i in stack:
    if stack:
        print(i,'check')
        stack.pop()

1 check
2 check


In [4]:
from collections import *
q = deque([1,2,3])

for i in range(len(q)):
    print(i)
    a = q.popleft()


0
1
2


In [7]:
N = int(input())
arr = input().strip()
stack = []
cnt = 0 
for i in arr:
    if len(stack) == 0:
        stack.append(i)

    elif i=='(' :
        stack.append(i) 
    elif i ==')' and stack[-1] == '(':
        
        stack.pop() 
        cnt+=1

print(cnt*2)
# print(stack)

10


In [9]:
from itertools import *
for i in permutations([1,2,3],2):
    print(i)

(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)


In [11]:
import tensorflow as tf
tf.linspace(1.5, 10.5, 3)

2023-03-03 15:05:33.090459: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-03 15:05:45.182751: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.5,  6. , 10.5], dtype=float32)>

In [1]:
import tensorflow as tf

tf.Variable(tf.ones(shape=(2,2)), name='W')

2023-03-03 15:36:58.086207: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-03 15:37:17.888602: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Variable 'W:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [8]:
tf.Variable([[1,1],[1,1]], shape=(2,2), name='W')

<tf.Variable 'W:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [14]:
W = tf.Variable(initial_value=[[1,1],[1,1]],shape = (2,2),name='W',)
W

<tf.Variable 'W:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [13]:
tf.Variable(initial_value=1,shape = (2,2),name='W',)

ValueError: In this `tf.Variable` creation, the initial value's shape (()) is not compatible with the explicitly supplied `shape` argument ((2, 2)).

In [2]:
import numpy as np
a = np.array([3,4,6,6])
a[6]

IndexError: index 6 is out of bounds for axis 0 with size 4