In [1]:
import numpy as np
np.eye(3)
n = np.arange(6).reshape(2,3)
print(n)
np.shape(n)

[[0 1 2]
 [3 4 5]]


(2, 3)

In [4]:
#:기준으로 좌측엔 행, 우측엔 열
n[:]

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
n[0:]

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
n[0,:]

array([0, 1, 2])

In [7]:
n[:,0]

array([0, 3])

In [15]:
import pandas as pd
pd.DataFrame(pd.Series([1,2,3],index =['a','b','c'], name='Title'))

Title
a      1
b      2
c      3